### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SzechuanSage** [miguelmota/fors#1]
Hello Miguel Mota

I was looking for a nested for loop like this to enhance or replace my code. I like what you have here. If I may, here are a few enhancements I would like to see:
1) There should be a separate min/max for each loop. This way, it allows for more customized scenarios, and if an array of min/max value objects was passed, it would remove the need for a depth parameter, since the depth would be the number of min/max value objects.
2) Skip (or continue) should be allowed in the loops. For example, if I have four loops, and I want to skip to the next index in the second loop, I should be allowed to do that without waiting for the loops to get that far on their own.

I have implemented both of these in my for-loops object already. And instead of passing a callback function and context, I pass an object that has an execute method and call that method for each iteration of the loops.

I know how to code JavaScript so I can submit a pull request if you like. And I can provide real-world use cases for the two enhancements I suggest. Please let me know if I should work on your module. Otherwise I am happy to continue using mine.

Kind regards
Szechuan Sage

**Comment by miguelmota** [comment]
Hi @SzechuanSage, those are great suggestions! can certainly implement no. 1, but curious to how you went about implementing no. 2. Pull requests are always welcomed : )

**Comment by SzechuanSage** [comment]
I'll describe it now, and do my best to send code on the week-end when I have a little bit more Sage-time.

Essentially, the callback function determines if a loop index needs to be skipped. It can return the index to skip. The loop can then use this index as the starting point for the increment code. I would really like to get the skip code working with your increment code. I use a for-loop for my increments.

**Comment by miguelmota** [comment]
Thanks @SzechuanSage for the explanation and PR. Fixed in  https://github.com/miguelmota/fors/pull/2
